name: Build and Deploy SurpriseMe

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-website:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build website
      run: npm run build
      
    - name: Upload website artifacts
      uses: actions/upload-artifact@v4
      with:
        name: website-dist
        path: dist/
        retention-days: 30

  build-extensions:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Create Chrome extension package
      run: |
        cd extension_chrome
        zip -r ../SurpriseMe-Chrome-v${{ github.run_number }}.zip . -x "*.md"
        
    - name: Create Firefox extension package
      run: |
        cd extension_firefox
        zip -r ../SurpriseMe-Firefox-v${{ github.run_number }}.zip . -x "*.md"
        
    - name: Upload Chrome extension
      uses: actions/upload-artifact@v4
      with:
        name: chrome-extension
        path: SurpriseMe-Chrome-v${{ github.run_number }}.zip
        retention-days: 90
        
    - name: Upload Firefox extension
      uses: actions/upload-artifact@v4
      with:
        name: firefox-extension
        path: SurpriseMe-Firefox-v${{ github.run_number }}.zip
        retention-days: 90

  deploy-to-github-pages:
    needs: build-website
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    permissions:
      contents: read
      pages: write
      id-token: write
      
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
    - name: Download website artifacts
      uses: actions/download-artifact@v4
      with:
        name: website-dist
        path: ./dist
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload to GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./dist
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4

  create-release:
    needs: [build-website, build-extensions]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Download Chrome extension
      uses: actions/download-artifact@v4
      with:
        name: chrome-extension
        
    - name: Download Firefox extension
      uses: actions/download-artifact@v4
      with:
        name: firefox-extension
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0.${{ github.run_number }}
        name: SurpriseMe v1.0.${{ github.run_number }}
        body: |
          ## SurpriseMe Extension Release v1.0.${{ github.run_number }}
          
          ### 🎨 What's New
          - Latest features and improvements
          - Bug fixes and performance optimizations
          - Updated browser compatibility
          
          ### 📦 Downloads
          - **Chrome Extension**: Download the `.zip` file and extract it for manual installation
          - **Firefox Extension**: Download the `.zip` file for manual installation or developer testing
          
          ### 🌐 Website
          The latest website is automatically deployed to GitHub Pages.
          
          ### 🔧 Installation Instructions
          #### Chrome/Edge/Brave/Vivaldi:
          1. Download `SurpriseMe-Chrome-v${{ github.run_number }}.zip`
          2. Extract the files
          3. Go to `chrome://extensions/`
          4. Enable "Developer mode"
          5. Click "Load unpacked" and select the extracted folder
          
          #### Firefox:
          1. Download `SurpriseMe-Firefox-v${{ github.run_number }}.zip`
          2. Go to `about:debugging`
          3. Click "This Firefox"
          4. Click "Load Temporary Add-on"
          5. Select the manifest.json file from the extracted folder
          
          ### 📞 Support
          For questions or issues, contact: harryhongyue@outlook.com
        files: |
          SurpriseMe-Chrome-v${{ github.run_number }}.zip
          SurpriseMe-Firefox-v${{ github.run_number }}.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  quality-checks:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run type checking
      run: npm run type-check
      continue-on-error: true
      
    - name: Run linting
      run: npm run lint
      continue-on-error: true
      
    - name: Validate Chrome extension manifest
      run: |
        echo "Validating Chrome extension manifest..."
        if [ -f "extension_chrome/manifest.json" ]; then
          echo "✅ Chrome manifest.json found"
          node -e "JSON.parse(require('fs').readFileSync('extension_chrome/manifest.json', 'utf8')); console.log('✅ Chrome manifest.json is valid JSON')"
        else
          echo "❌ Chrome manifest.json not found"
          exit 1
        fi
        
    - name: Validate Firefox extension manifest
      run: |
        echo "Validating Firefox extension manifest..."
        if [ -f "extension_firefox/manifest.json" ]; then
          echo "✅ Firefox manifest.json found"
          node -e "JSON.parse(require('fs').readFileSync('extension_firefox/manifest.json', 'utf8')); console.log('✅ Firefox manifest.json is valid JSON')"
        else
          echo "❌ Firefox manifest.json not found"
          exit 1
        fi