name: Release Extensions to Stores

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.0.0)'
        required: true
        type: string

jobs:
  prepare-chrome-store:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Update Chrome extension version
      run: |
        VERSION="${{ github.event.inputs.version || github.ref_name }}"
        VERSION=${VERSION#v}  # Remove 'v' prefix if present
        
        cd extension_chrome
        # Update version in manifest.json
        sed -i "s/\"version\": \"[^\"]*\"/\"version\": \"$VERSION\"/" manifest.json
        echo "Updated Chrome extension version to $VERSION"
        
    - name: Create Chrome store package
      run: |
        cd extension_chrome
        zip -r ../chrome-store-package.zip . -x "*.md" "*.txt"
        
    - name: Upload Chrome store package
      uses: actions/upload-artifact@v4
      with:
        name: chrome-store-package
        path: chrome-store-package.zip
        retention-days: 30

  prepare-firefox-store:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Update Firefox extension version
      run: |
        VERSION="${{ github.event.inputs.version || github.ref_name }}"
        VERSION=${VERSION#v}  # Remove 'v' prefix if present
        
        cd extension_firefox
        # Update version in manifest.json
        sed -i "s/\"version\": \"[^\"]*\"/\"version\": \"$VERSION\"/" manifest.json
        echo "Updated Firefox extension version to $VERSION"
        
    - name: Create Firefox store package
      run: |
        cd extension_firefox
        zip -r ../firefox-store-package.zip . -x "*.md" "*.txt"
        
    - name: Upload Firefox store package
      uses: actions/upload-artifact@v4
      with:
        name: firefox-store-package
        path: firefox-store-package.zip
        retention-days: 30

  create-store-release:
    needs: [prepare-chrome-store, prepare-firefox-store]
    runs-on: ubuntu-latest
    
    steps:
    - name: Download Chrome package
      uses: actions/download-artifact@v4
      with:
        name: chrome-store-package
        
    - name: Download Firefox package
      uses: actions/download-artifact@v4
      with:
        name: firefox-store-package
        
    - name: Create store release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: store-${{ github.event.inputs.version || github.ref_name }}
        name: Store Release ${{ github.event.inputs.version || github.ref_name }}
        body: |
          ## 🏪 Browser Store Release
          
          This release contains packages ready for submission to browser extension stores.
          
          ### 📦 Store Packages
          - **chrome-store-package.zip**: Ready for Chrome Web Store submission
          - **firefox-store-package.zip**: Ready for Mozilla Add-ons submission
          
          ### 📋 Submission Checklist
          
          #### Chrome Web Store:
          - [ ] Upload `chrome-store-package.zip` to [Chrome Web Store Developer Dashboard](https://chrome.google.com/webstore/devconsole/)
          - [ ] Update store listing description and screenshots
          - [ ] Set pricing and distribution
          - [ ] Submit for review
          
          #### Mozilla Add-ons:
          - [ ] Upload `firefox-store-package.zip` to [Mozilla Add-on Developer Hub](https://addons.mozilla.org/developers/)
          - [ ] Update add-on description and screenshots
          - [ ] Submit for review
          
          #### Edge Add-ons:
          - [ ] Upload `chrome-store-package.zip` to [Microsoft Edge Add-ons](https://partner.microsoft.com/dashboard/microsoftedge/)
          - [ ] Update store listing
          - [ ] Submit for review
          
          ### 🔗 Store Links (update after approval):
          - Chrome: https://chrome.google.com/webstore/detail/surpriseme/[ID]
          - Firefox: https://addons.mozilla.org/firefox/addon/surpriseme/
          - Edge: https://microsoftedge.microsoft.com/addons/detail/surpriseme/[ID]
          
          ### 📞 Contact
          For store submission questions: harryhongyue@outlook.com
        files: |
          chrome-store-package.zip
          firefox-store-package.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}